# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tschatgpt-linebot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://tsnickliu.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4f673a7840ef48af8c826cff1d86e38b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3a87cb9c05e24f59b18faabe7edf784d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: tsnickliu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4f673a7840ef48af8c826cff1d86e38b }}/gpt-ai-assistant:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tschatgpt-linebot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c559df6a2ec4a47a7172be6b528d81f }}
        images: 'tsnickliu.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4f673a7840ef48af8c826cff1d86e38b }}/gpt-ai-assistant:${{ github.sha }}'